package model;
// Generated 19/06/2011 17:24:10 by Hibernate Tools 3.2.1.GA



/**
 * Teste generated by hbm2java
 */
public class Teste  implements java.io.Serializable {


     private Integer idteste;

    public Teste() {
    }

    public Teste(Integer idteste) {
       this.idteste = idteste;
    }
   
    public Integer getIdteste() {
        return this.idteste;
    }
    
    public void setIdteste(Integer idteste) {
        this.idteste = idteste;
    }




}


